In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes
#Importing regression models
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [15]:
diab=load_diabetes()
df = pd.DataFrame(data= np.c_[diab['data'], diab['target']],
                     columns= diab['feature_names'] + ['target'])
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

In [32]:
x,y=load_diabetes(return_X_y=1)
#y=y.reshape(len(y),1)

array([[ 0.04,  0.05,  0.06, ..., -0.  ,  0.02, -0.02],
       [-0.  , -0.04, -0.05, ..., -0.04, -0.07, -0.09],
       [ 0.09,  0.05,  0.04, ..., -0.  ,  0.  , -0.03],
       ...,
       [ 0.04,  0.05, -0.02, ..., -0.01, -0.05,  0.02],
       [-0.05, -0.04,  0.04, ...,  0.03,  0.04, -0.03],
       [-0.05, -0.04, -0.07, ..., -0.04, -0.  ,  0.  ]])

In [22]:
print('No. of null values in x:',np.isnan(x).any().sum())
print('No. of Null values in y:',np.isnan(y).any().sum())

No. of null values in x: 0
No. of Null values in y: 0


In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)
print(y_test)

[ 78. 152. 200.  59. 311. 178. 332. 132. 156. 135. 220. 233.  91.  51.
 195. 109. 217.  94.  89. 111. 129. 181. 168.  97. 115. 202.  84. 147.
 253. 144. 262. 115.  68.  65. 252. 212. 142. 215. 180. 163. 151. 283.
  66.  83. 214. 189. 302.  93. 178. 241.  52. 144. 102. 200. 232.  97.
 109.  55.  63.  98.  88. 233. 235.  97. 243.  59. 138. 220. 137.  72.
 109.  71.  74. 219. 196. 170. 199.  71. 155.  52.  63.  88.  97. 100.
  64. 107.  49.  60. 346.]


In [24]:
#multiple linear regression
reg1=LinearRegression()
reg1.fit(x_train,y_train)
#Decision tree regression
reg2=DecisionTreeRegressor()
reg2.fit(x_train,y_train)
#Random forest regression
reg3=RandomForestRegressor(n_estimators=100,random_state=1)
reg3.fit(x_train,y_train)
#Polynomial regression
poly_reg=PolynomialFeatures(degree=5)
x_poly=poly_reg.fit_transform(x_train)
reg4=LinearRegression()
reg4.fit(x_poly,y_train)
#Support vector regression
reg5=SVR(kernel='rbf')
reg5.fit(x_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [28]:
y_pred1=reg1.predict(x_test)
y_pred2=reg2.predict(x_test)
y_pred3=reg3.predict(x_test)
y_pred4=reg4.predict(poly_reg.transform(x_test))
y_pred5=reg5.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred1.reshape(len(y_pred1),1),y_pred2.reshape(len(y_pred2),1),
                      y_pred3.reshape(len(y_pred3),1),y_pred4.reshape(len(y_pred4),1),y_pred5.reshape(len(y_pred5),1)),1))

[[ 7.80e+01  1.19e+02  9.50e+01  1.35e+02 -3.49e+02  1.35e+02]
 [ 1.52e+02  1.11e+02  7.70e+01  1.09e+02  7.75e+01  1.32e+02]
 [ 2.00e+02  1.85e+02  9.60e+01  1.57e+02  4.26e+02  1.44e+02]
 [ 5.90e+01  6.80e+01  9.30e+01  7.92e+01  1.92e+02  1.19e+02]
 [ 3.11e+02  1.71e+02  1.64e+02  1.49e+02  2.44e+02  1.55e+02]
 [ 1.78e+02  1.90e+02  2.97e+02  2.53e+02  2.19e+02  1.55e+02]
 [ 3.32e+02  2.19e+02  2.37e+02  2.14e+02  1.40e+02  1.63e+02]
 [ 1.32e+02  1.20e+02  4.90e+01  9.17e+01  2.02e+02  1.33e+02]
 [ 1.56e+02  1.57e+02  2.52e+02  1.47e+02 -4.83e+02  1.38e+02]
 [ 1.35e+02  1.29e+02  1.18e+02  9.10e+01  1.07e+02  1.28e+02]
 [ 2.20e+02  2.14e+02  2.72e+02  1.87e+02  1.06e+01  1.52e+02]
 [ 2.33e+02  2.03e+02  1.71e+02  1.95e+02  9.98e+02  1.52e+02]
 [ 9.10e+01  8.84e+01  1.18e+02  1.07e+02  2.05e+02  1.25e+02]
 [ 5.10e+01  7.20e+01  9.20e+01  9.27e+01  3.18e+02  1.22e+02]
 [ 1.95e+02  2.37e+02  2.97e+02  2.65e+02  3.75e+02  1.58e+02]
 [ 1.09e+02  2.06e+02  2.81e+02  2.13e+02  1.52e+02  1.

In [29]:
print('Multiple linear regression accuracy:',r2_score(y_test,y_pred1))
print('Decision tree regression accuracy:',r2_score(y_test,y_pred2))
print('Random forest regression accuracy:',r2_score(y_test,y_pred3))
print('Polynomial regression accuracy:',r2_score(y_test,y_pred4))
print('Support vector regression accuracy:',r2_score(y_test,y_pred5))


Multiple linear regression accuracy: 0.43843604017332694
Decision tree regression accuracy: -0.23373117962726786
Random forest regression accuracy: 0.2837289750645179
Polynomial regression accuracy: -48.115561041813535
Support vector regression accuracy: 0.17710151701511323


In [31]:
reg1.predict([[0.038076 ,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019908,-0.017646]])

array([203.36])