In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.style as atl

In [33]:
df=pd.read_csv('50_Startups.csv')
df.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [34]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

# Data Preprocessing

Encoding categorical variable

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encode',OneHotEncoder(),[3])],remainder='passthrough')
x=ct.fit_transform(x)

In [36]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [60]:
from sklearn.model_selection import train_test_split
validate=0.2
seed=0
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=validate,random_state=seed)

In [61]:
print(x_test.shape)

(10, 6)


# Training the model

In [62]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [63]:
y_pred=regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1),
                      (y_test.reshape(len(y_test),1)-(y_pred.reshape(len(y_pred),1)))),axis=1))

[[103015.2  103282.38    267.18]
 [132582.28 144259.4   11677.12]
 [132447.74 146121.95  13674.21]
 [ 71976.1   77798.83   5822.73]
 [178537.48 191050.39  12512.91]
 [116161.24 105008.31 -11152.93]
 [ 67851.69  81229.06  13377.37]
 [ 98791.73  97483.56  -1308.17]
 [113969.44 110352.25  -3617.19]
 [167921.07 166187.94  -1733.13]]


In [57]:
'''print(y_pred.reshape(len(y_pred),1),end=' | ')
print(y_test.reshape(len(y_test),1),end=' | ')
print(y_test-y_pred)'''

"print(y_pred.reshape(len(y_pred),1),end=' | ')\nprint(y_test.reshape(len(y_test),1),end=' | ')\nprint(y_test-y_pred)"

In [67]:
print(regressor.coef_)
print(regressor.intercept_)

[ 8.66e+01 -8.73e+02  7.86e+02  7.73e-01  3.29e-02  3.66e-02]
42467.52924854249
